site_name: QFlux Docs
theme:
  name: material
  features:
    - content.code.copy
    
extra_css:
- stylesheets/extra.css

extra_javascript:
- javascripts/mathjax.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc: 
      toc_depth: 3

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # if your package is in a src folder (src-layout)
